# Copyright 2019-2022 DADoES, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the root directory in the "LICENSE" file or at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#The package.yml file contains the location of models to be loaded from Blender files.
#The name of the objects map to the name of a collection in the blender file.

# This package uses bundled package data. The data is located in the package itself under
# a sub directory defined by the 'example' logical name.
# The logical name is then used in the "objects" block to refer to that location.
# For instance, "example:Yoyo.blend" refers to "volumes/e66.../Yoyo.blend" in the
# package directory
volumes:
  example: '05172bac-03c6-4151-bfb9-870766b1b1e0'

# Define objects.
objects:

  YoYo:
    filename: example:YoYo_greenLogo.blend

  BubbleBottle:
    filename: example:BubbleBottle_greenLogo.blend

  Skateboard:
    filename: example:Skateboard_v2.blend

  Cube:
    filename: example:Cube.blend

  Mix Cube:
    filename: example:MixCube.blend

  PlayDough:
    filename: example:PlayDough_greenLogo.blend

  Light Wooden Box:
    filename: example:Containers/LightWoodenBox.blend

  Dark Wooden Box:
    filename: example:Containers/DarkWoodenBox.blend

  Blue Tub:
    filename: example:Containers/BlueTub.blend

  Orange Tub:
    filename: example:Containers/OrangeTub.blend

  Green Tub:
    filename: example:Containers/GreenTub.blend

  Clear Tub:
    filename: example:Containers/ClearTub.blend

  Gray Tub:
    filename: example:Containers/GrayTub.blend

  Yellow Bowl:
    filename: example:Containers/YellowBowl.blend

  Purple Bowl:
    filename: example:Containers/PurpleBowl.blend

  Short Basket:
    filename: example:Containers/ShortBasket.blend

  Tall Basket:
    filename: example:Containers/TallBasket.blend

  Plane Floor:
    filename: example:Floors/PlaneFloor.blend

  Tile:
    filename: example:Floors/Tile.blend

  Cobbles:
    filename: example:Floors/Cobble.blend

  Wood:
    filename: example:Floors/Wood.blend

  Hardwood:
    filename: example:Floors/Wood03.blend

  Rocks:
    filename: example:Floors/Rock.blend

  Granite:
    filename: example:Floors/Granite.blend

  Metal:
    filename: example:Floors/Metal.blend